services:
  app:
    container_name: app-dev
    image: app-dev-i
    build:
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
        - action: rebuild
          path: package.json
volumes:
  node_modules:
